-- MySQL Script generated by MySQL Workbench
-- 03/21/16 18:00:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8 ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`Inventario` (
  `id_inv` INT NOT NULL AUTO_INCREMENT,
  `cod_prod_inv` INT NOT NULL,
  `nombre_inv` VARCHAR(45) NOT NULL,
  `tipo_producto_inv` VARCHAR(45) NOT NULL,
  `iva_inv` VARCHAR(45) NOT NULL,
  `imagen` LONGBLOB NULL,
  `ruta_imagen_inv` VARCHAR(45) NULL,
  `valor_neto_compra_inv` INT NOT NULL,
  `valor_neto_venta_inv` INT NOT NULL,
  PRIMARY KEY (`id_inv`),
  UNIQUE INDEX `id_inv_UNIQUE` (`id_inv` ASC),
  UNIQUE INDEX `cod_inv_UNIQUE` (`cod_prod_inv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`Proveedores` (
  `id_prov` INT NOT NULL AUTO_INCREMENT,
  `nit_prov` VARCHAR(45) NOT NULL,
  `nombre_prov` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion_mov` VARCHAR(45) NOT NULL,
  `ciudad_mov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prov`),
  UNIQUE INDEX `id_prov_UNIQUE` (`id_prov` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`Movimiento` (
  `id_mov` INT NOT NULL AUTO_INCREMENT,
  `fecha_mov` DATE NOT NULL,
  `cod_proveedor_mov` INT NOT NULL,
  `cantidad_prod_mov` INT NOT NULL,
  `tipo_movimiento_mov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mov`),
  UNIQUE INDEX `id_mov_UNIQUE` (`id_mov` ASC),
  INDEX `mov_prov_idx` (`cod_proveedor_mov` ASC),
  CONSTRAINT `mov_prov`
    FOREIGN KEY (`cod_proveedor_mov`)
    REFERENCES `inventario`.`Proveedores` (`id_prov`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`Inventario_Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`Inventario_Movimiento` (
  `id_inv_mov` INT NOT NULL AUTO_INCREMENT,
  `cod_inv_mov` INT NOT NULL,
  `cod_mov_mov` INT NOT NULL,
  PRIMARY KEY (`id_inv_mov`),
  UNIQUE INDEX `id_inv_mov_UNIQUE` (`id_inv_mov` ASC),
  INDEX `inv_mov_idx` (`cod_inv_mov` ASC),
  INDEX `invmov_mov_idx` (`cod_mov_mov` ASC),
  CONSTRAINT `invmov_inv`
    FOREIGN KEY (`cod_inv_mov`)
    REFERENCES `inventario`.`Inventario` (`id_inv`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `invmov_mov`
    FOREIGN KEY (`cod_mov_mov`)
    REFERENCES `inventario`.`Movimiento` (`id_mov`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
